theme: jekyll-theme-minimal
title: "Andrew Spiers: Black Hole and Gravitational Wave Researcher: Homepage"
description: "I am a PhD scientist at the University of Southampton, soon to graduate and begin a Research Associate position at the University of Nottingham."


# Site Settings
locale                   : "UK"
title                    : "Andrew Spiers"
title_separator          : "-"
name                     : &name "Andrew Spiers"
description              : &description "I am a PhD student at the University of Southampton. My research concerns improving models of gravitational wave sources."
url                      : https://andrewspiers.github.io/ # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "arcs1n18.github.io"
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : false #change to true to add link to talkmap on talks page
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages" # "master", "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  path                   : # blank (default) uses feed.xml

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : 
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles


# Analytics
analytics:
  provider               :  "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :



# Site Author
author:
  name             : "Andrew Spiers"
  avatar           : "profile.png"
  bio              : "Your biography for the left-hand sidebar"
  location         : "University of Southampton"
  googlescholar    : "http://yourfullgooglescholarurl.com"
  email            : "A.R.C.SPIERS@SOTON.AC.UK"
  github           : "https://github.com/arcs1n18/"
  orcid            : "http://orcid.org/yourorcidurl"


# The largest heading test
